"""added farm name to farm

Revision ID: 0185b80a82f9
Revises: fa794ff8da1c
Create Date: 2019-05-27 21:26:04.970706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0185b80a82f9'
down_revision = 'fa794ff8da1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('farm_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'farm_name')
    # ### end Alembic commands ###
