"""altered alerts

Revision ID: 152a8279d3ae
Revises: 8939f008359f
Create Date: 2019-04-28 16:36:25.925769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152a8279d3ae'
down_revision = '8939f008359f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('tag_name', sa.String(length=255), nullable=True))
    op.drop_column('alerts', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('alerts', 'tag_name')
    # ### end Alembic commands ###
