"""created settings table

Revision ID: 931e06bb286f
Revises: 93e8840b87ba
Create Date: 2019-03-26 16:34:44.553001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931e06bb286f'
down_revision = '93e8840b87ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('min_temperature', sa.Integer(), nullable=True),
                    sa.Column('max_temperature', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
