"""added rule_value

Revision ID: 9b4c6ff76b5e
Revises: f1ad1b054691
Create Date: 2019-04-30 15:40:39.913592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4c6ff76b5e'
down_revision = 'f1ad1b054691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('rule_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'rule_value')
    # ### end Alembic commands ###
