"""added emergency contact to settings

Revision ID: 9c6ae3be90ab
Revises: 931e06bb286f
Create Date: 2019-03-26 16:52:19.505268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6ae3be90ab'
down_revision = '931e06bb286f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('emergency_email', sa.String(length=128), nullable=True))
    op.add_column('settings', sa.Column('emergency_phone', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'emergency_phone')
    op.drop_column('settings', 'emergency_email')
    # ### end Alembic commands ###
