"""added feed level to sensor table

Revision ID: a670e9011f07
Revises: 951de0bf9891
Create Date: 2019-05-26 00:41:39.763244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a670e9011f07'
down_revision = '951de0bf9891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dht_sensor_readings', sa.Column('feed_level', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dht_sensor_readings', 'feed_level')
    # ### end Alembic commands ###
