"""added weight sensor table

Revision ID: e34705dc3219
Revises: 9c6ae3be90ab
Create Date: 2019-04-10 19:07:47.214462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34705dc3219'
down_revision = '9c6ae3be90ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=True),
    sa.Column('reading_time', sa.Time(), nullable=True),
    sa.Column('weight', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_sensor_readings')
    # ### end Alembic commands ###
