"""rules table

Revision ID: f1ad1b054691
Revises: 152a8279d3ae
Create Date: 2019-04-30 15:22:24.594435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ad1b054691'
down_revision = '152a8279d3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.String(length=255), nullable=True),
    sa.Column('rule_type', sa.String(length=255), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    # ### end Alembic commands ###
