"""added devices and user devices table

Revision ID: fa794ff8da1c
Revises: a670e9011f07
Create Date: 2019-05-27 20:07:09.902666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa794ff8da1c'
down_revision = 'a670e9011f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('model', sa.String(length=255), nullable=True),
                    sa.Column('serial', sa.String(length=255), nullable=True),
                    sa.Column('acquired_on', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_devices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('device_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_foreign_key(None, 'rules', 'alerts', ['alert_id'], ['id'])
    op.add_column('users', sa.Column('user_type_id',
                                     sa.SmallInteger(), default=0, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type_id')
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_table('user_devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
